import React from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, Shield, Scale, FileText, AlertCircle } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#07090f] text-[#eef6ff] selection:bg-sky-500/30">
      <div className="orb orb1"></div>
      <div className="orb orb2"></div>

      <nav className="fixed top-0 left-0 right-0 z-50 px-6 py-6 flex items-center justify-between backdrop-blur-md border-b border-white/5">
        <a href="/" className="flex items-center gap-2 text-[#8899aa] hover:text-[#eef6ff] transition-colors font-medium text-sm">
          <ArrowLeft size={16} />
          Back to Home
        </a>
        <a href="/" className="logo" style={{ textDecoration: 'none' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', fontSize: '22px', fontWeight: 800, letterSpacing: '-0.5px', color: '#eef6ff' }}>
            <div style={{ position: 'relative', width: '30px', height: '24px', flexShrink: 0 }}>
              <div style={{ position: 'absolute', width: '24px', height: '16px', background: 'rgba(125,211,252,0.2)', border: '1px solid rgba(125,211,252,0.4)', borderRadius: '5px', top: 0, left: '6px' }} />
              <div style={{ position: 'absolute', width: '24px', height: '16px', background: '#131820', border: '1px solid rgba(125,211,252,0.6)', borderRadius: '5px', bottom: 0, left: 0 }}>
                <div style={{ position: 'absolute', top: '5px', left: '5px', right: '5px', height: '2px', borderRadius: '1px', background: 'rgba(125,211,252,0.5)' }} />
              </div>
            </div>
            Ankit
          </div>
        </a>
        <div className="w-24" /> {/* Spacer */}
      </nav>

      <main className="max-w-3xl mx-auto px-6 pt-32 pb-24">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4">Terms of Service</h1>
          <p className="text-[#8899aa] mb-12 font-medium">Last updated: March 11, 2026</p>

          <div className="space-y-12">
            <section>
              <div className="flex items-center gap-3 mb-4 text-sky-400">
                <AlertCircle size={24} />
                <h2 className="text-xl font-bold text-[#eef6ff]">1. AI Accuracy Disclaimer</h2>
              </div>
              <div className="prose prose-invert max-w-none text-[#8899aa] leading-relaxed space-y-4">
                <p>
                  Ankit uses advanced artificial intelligence to generate study materials. While we strive for excellence, AI can occasionally produce inaccurate, incomplete, or "hallucinated" information.
                </p>
                <p className="bg-sky-500/5 border border-sky-500/20 rounded-xl p-4 text-sky-200 text-sm">
                  <strong>Important:</strong> You are responsible for verifying all generated flashcards against your original source material before relying on them for examinations or clinical practice.
                </p>
              </div>
            </section>

            <section>
              <div className="flex items-center gap-3 mb-4 text-sky-400">
                <Shield size={24} />
                <h2 className="text-xl font-bold text-[#eef6ff]">2. Medical & Professional Disclaimer</h2>
              </div>
              <div className="prose prose-invert max-w-none text-[#8899aa] leading-relaxed">
                <p>
                  The content generated by Ankit is for <strong>educational purposes only</strong>. It does not constitute medical advice, diagnosis, or treatment. Never disregard professional medical advice or delay seeking it because of something you have read in a flashcard generated by this service.
                </p>
              </div>
            </section>

            <section>
              <div className="flex items-center gap-3 mb-4 text-sky-400">
                <FileText size={24} />
                <h2 className="text-xl font-bold text-[#eef6ff]">3. User Content & Uploads</h2>
              </div>
              <div className="prose prose-invert max-w-none text-[#8899aa] leading-relaxed space-y-4">
                <p>
                  When you upload files (PDFs, PPTXs) to Ankit, you retain all ownership rights to your original content.
                </p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><strong>License to Process:</strong> You grant Ankit a limited, non-exclusive license to process your content solely for the purpose of generating flashcards.</li>
                  <li><strong>Copyright Compliance:</strong> You represent that you have the legal right to upload and process the materials you provide. Do not upload content that infringes on the intellectual property rights of others.</li>
                </ul>
              </div>
            </section>

            <section>
              <div className="flex items-center gap-3 mb-4 text-sky-400">
                <Scale size={24} />
                <h2 className="text-xl font-bold text-[#eef6ff]">4. Subscription & Fair Use</h2>
              </div>
              <div className="prose prose-invert max-w-none text-[#8899aa] leading-relaxed space-y-4">
                <p>
                  Ankit offers free and paid (Pro) tiers. 
                </p>
                <ul className="list-disc pl-5 space-y-2">
                  <li><strong>Billing:</strong> Subscriptions are billed in advance on a recurring basis.</li>
                  <li><strong>Refunds:</strong> Due to the high computational costs of AI generation, we generally do not offer refunds once a deck has been generated.</li>
                  <li><strong>Fair Use:</strong> "Unlimited" generation is subject to a fair use policy to prevent system abuse.</li>
                </ul>
              </div>
            </section>

            <section>
              <div className="flex items-center gap-3 mb-4 text-sky-400">
                <AlertCircle size={24} />
                <h2 className="text-xl font-bold text-[#eef6ff]">5. Affiliation Disclaimer</h2>
              </div>
              <div className="prose prose-invert max-w-none text-[#8899aa] leading-relaxed">
                <p>
                  Ankit is an independent tool and is not affiliated with, endorsed by, or associated with the official Anki software (AnkiWeb/AnkiMobile) or its creators. "Anki" is a registered trademark of its respective owners.
                </p>
              </div>
            </section>

            <section className="pt-8 border-t border-white/5">
              <p className="text-sm text-[#8899aa]">
                By using Ankit, you agree to these terms. If you do not agree, please do not use the service. For any questions regarding these terms, please contact us at support@ankit.study.
              </p>
            </section>
          </div>
        </motion.div>
      </main>

      <footer className="max-w-3xl mx-auto px-6 py-12 border-t border-white/5 text-center">
        <p className="text-xs text-[#8899aa]">© 2026 Ankit. All rights reserved.</p>
      </footer>
    </div>
  );
}
